### ISSUE TITLE
SDK needs a tear down method

### ISSUE THREAD

**Issue by eivindingebrigtsen** [BROKLab/brok-monorepo#7]
When including SDK in tests the SDK produces an error as it is not able to be killed.
```
  ●  PBKDF2REQUEST
      let sdk;
      async function main() {
        sdk = await SDK.init({
          ceramicUrl: CERAMIC_NODE,
          ethereumRpc: ETHEREUM_RPC,
          seed: SDK_SEED,
      ...
      at pbkdf2 (node_modules/@ethersproject/pbkdf2/src.ts/pbkdf2.ts:13:27)
      at mnemonicToSeed (node_modules/@ethersproject/hdnode/src.ts/index.ts:315:18)
      at Function.Object.<anonymous>.HDNode.fromMnemonic (node_modules/@ethersproject/hdnode/src.ts/index.ts:271:33)
      at new Wallet (node_modules/@ethersproject/wallet/src.ts/index.ts:64:37)
      at Wallet.Object.<anonymous>.Wallet.connect (node_modules/@ethersproject/wallet/src.ts/index.ts:114:16)
      at Function.initWallet (node_modules/@brok/sdk/src/sdk.ts:39:43)
      at Function.init (node_modules/@brok/sdk/src/sdk.ts:27:31)
      at init (src/ceramic/index.js:5:19)
      at Object.main (src/ceramic/index.js:12:1)
      at Object.require (src/handlers/findCaptableHandler.js:2:35)
      at Object.require (src/main.js:4:33)
      at Object.<anonymous> (test/api.test.js:1:24)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:317:13)
      at runJest (node_modules/@jest/core/build/runJest.js:407:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:338:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:190:3)
```

This is caused by an open handler being left when the server is torn down.
Suggestion to add a close method, that kills all open connections and shuts down the SDK, that can be called on server shutdown.

**Comment by RobertoSnap** [comment]
Added `await sdk.close() ` in SDK version 0.9.0
